webtalk_init -webtalk_dir D:\\AGH_magisterskie\\SDUP\\SDUP_BWT_transformata\\BWT_cordic\\BWT_cordic.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2023-06-18 14:29:38" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ual9mhs9n1934vupci0or7b9e9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.273 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1687091118586" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1687091118586"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1687091378095"
webtalk_transmit -clientid 288290145 -regid "" -xml D:\\AGH_magisterskie\\SDUP\\SDUP_BWT_transformata\\BWT_cordic\\BWT_cordic.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\AGH_magisterskie\\SDUP\\SDUP_BWT_transformata\\BWT_cordic\\BWT_cordic.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\AGH_magisterskie\\SDUP\\SDUP_BWT_transformata\\BWT_cordic\\BWT_cordic.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
